### ISSUE TITLE
GH enterprise support?

### ISSUE THREAD

**Issue by jasonkarns** [sindresorhus/github-tab-size#7]
Any chance of getting this to work with GH enterprise?

**Comment by sindresorhus** [comment]
A good PR would be merged, but I'm not very interested myself.

See https://github.com/sindresorhus/github-notifier-chrome/blob/1495a214aefadffbb83cdd5d383aeb23f28f38c2/extension/options.html#L48-L53 on how it should be implemented.

**Comment by sindresorhus** [comment]
Actually no. I'm not interested in maintaining something like that.

**Comment by mkordas** [comment]
@sindresorhus, any chance you will reconsider approving PR with support for this? The simplest way would be to enable this style on any page matching `github*.com`, not only `github.com`.

**Comment by sindresorhus** [comment]
@mkordas No, not interested in the complexity. I don't think the permission globbing works like that and even if it did, it would be too loose. It would also mean I would need to ask for more permissions from people, even though very few would need this feature. I could add an option, but there's so much overhead and boilerplate in creating a settings panel for Chrome extensions. Feel free to fork and create something based on this, though.

**Comment by mkordas** [comment]
@sindresorhus, thanks for your response. Looks like I need to do a fork.

**Comment by sindresorhus** [comment]
I would be happy to link to it.
