### ISSUE TITLE
adding option page

### ISSUE THREAD

**Issue by xizhonghua** [sindresorhus/github-tab-size#9]
Hi, would you able to add an option page to let the user choose his favorite tab size (like 2 for me)?

**Comment by sindresorhus** [comment]
From the top of the readme:

> It's intentionally simple and I'm not interested in adding anything more to it.

**Comment by cowgill** [comment]
@sindresorhus, Would you accept a pull request for this feature?

**Comment by sindresorhus** [comment]
No
